### ISSUE TITLE
requiring 'gem facets' breaks Rails 3.2.1 / facets 2.9.3

### ISSUE THREAD

**Issue by tilo** [rubyworks/facets#55]
I have a brand-new Rails 3.2.1 project, which requires facets, and after you run "bundle install",
when you run "rails console" , this happens:

```
$ rails --version
3.2.1
$ rails new example
$ cd example
$ vi Gemfile
$ bundle install

$ rails c
/Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/engine.rb:504:in `block in initializers': undefined method `initializers' for #<Instance:0x007fd52b3ae7d0 @delegate=:all> (NoMethodError)
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/engine.rb:500:in `each'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/engine.rb:500:in `initializers'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/application.rb:202:in `initializers'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/initializable.rb:54:in `run_initializers'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/application.rb:136:in `initialize!'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/railtie/configurable.rb:30:in `method_missing'
        from /private/tmp/DELETEME/config/environment.rb:5:in `<top (required)>'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `block in require'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:236:in `load_dependency'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/activesupport-3.2.1/lib/active_support/dependencies.rb:251:in `require'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/application.rb:103:in `require_environment!'
        from /Users/myusername/.rvm/gems/ruby-1.9.2-p180@rails_3.2/gems/railties-3.2.1/lib/rails/commands.rb:40:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by ioquatix** [comment]
If this is still a problem please re-open it with a specific test case so we can fix. Thanks so much for all the details you provided. We definitely want to be compatible with rails if possible.
